# Generated by Django 5.2.4 on 2025-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_joined_date_members_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
